#:kivy 2.3.1

<MainScreen>:
    BoxLayout:
        orientation: 'vertical'
        spacing: 0
        size_hint: (1, 1)
        color: (0.5, 0.5, 0.5, 1)
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            height: 50
            padding: 15, 10
            Label:
                id: "title"
                text: "Marvis"
                pos_hint_y: 0
                font_size: 22
